### ISSUE TITLE
使用 CI 即時測試 PR

### ISSUE THREAD

**Issue by ItzMiracleOwO** [RadishTeam/RadishBot#19]
### 你希望有什麽功能？

使用 CI 即時測試 PR

### 為什麼？

有助開發

### 其他細節

文檔鏈接 https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

**Comment by ItzMiracleOwO** [comment]
@WinsonOTP

**Comment by nk980113** [comment]
英文爛啦QQ

**Comment by ItzMiracleOwO** [comment]
commit之後自動在虛擬機跑一次看有沒有報錯
測試一邊 沒有報錯就pass 有的話就不能merge

**Comment by nk980113** [comment]
🤔 
可

**Comment by ItzMiracleOwO** [comment]
問題是我沒權限搞 建議開個organization然後把專案拉進去 然後再給權限 這樣會比較方便 @WinsonOTP

**Comment by WinsonOTP** [comment]
> 英文爛啦QQ @ItzMiracleOwO 可以稍微解釋一下這是做什麼用的嗎？

題外話 你英文爛？？？==

**Comment by WinsonOTP** [comment]
> 問題是我沒權限搞 建議開個organization然後把專案拉進去 然後再給權限 這樣會比較方便 @WinsonOTP

什麼概念owo？

**Comment by ItzMiracleOwO** [comment]
> > 問題是我沒權限搞 建議開個organization然後把專案拉進去 然後再給權限 這樣會比較方便 @WinsonOTP
> 
> 什麼概念owo？

🤔就organization
