### ISSUE TITLE
建議加入的 GitHub Apps

### ISSUE THREAD

**Issue by ItzMiracleOwO** [RadishTeam/RadishBot#22]
### 你希望有什麽功能？

加入 GitHub Apps

https://github.com/marketplace/stale
https://github.com/marketplace/codefactor
https://github.com/marketplace/circleci

### 為什麼？

幫助專案變得更好

**Comment by nk980113** [comment]
O
X
🤔

**Comment by ItzMiracleOwO** [comment]
why not code factor 🤔
