### ISSUE TITLE
改變env 使用方式

### ISSUE THREAD

**Issue by nk980113** [RadishTeam/RadishBot#33]
env全部改大寫（基本上env也只能大寫）
例如：process.env.CLIENT_ID

**Comment by ItzMiracleOwO** [comment]
https://stackoverflow.com/questions/673055/correct-bash-and-shell-script-variable-capitalization
![image](https://user-images.githubusercontent.com/76854136/144837571-d4c8ac0f-5e2a-4afe-bffa-6320b670c7ae.png)

@nk980113

**Comment by nk980113** [comment]
🤔 
All environment variables should be uppercase

**Comment by nk980113** [comment]
點進去看了一下
那是shell的命名規則

**Comment by nk980113** [comment]
https://nodejs.org/api/process.html#processenv

**Comment by ItzMiracleOwO** [comment]
除了BASH_VERSION SHELL 以外其他東西都可以lower case 🤔

**Comment by ItzMiracleOwO** [comment]
https://stackoverflow.com/questions/46747839/why-are-node-js-environment-variables-written-in-all-caps-and-underscores

> In fact, these are not environment variables, but environment constants in the scope of your app.
> It's a convention to name constants in capital letters.
> 
> The underscore just makes it more readable.
> 
> You can still use camelCase if you prefer, it's a matter of choice.

**Comment by nk980113** [comment]
@ItzMiracleOwO I **do not prefer** using camelCase when naming .env variables

**Comment by ItzMiracleOwO** [comment]
fine
change it urself

**Comment by ItzMiracleOwO** [comment]
just create pr

**Comment by ItzMiracleOwO** [comment]
hm

**Comment by ItzMiracleOwO** [comment]
@nk980113
